name: Build Job Electron

on:
  workflow_dispatch

jobs:
  build:
    name: Build Electron desktop app for Linux, Win, OS X
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn dist

      - name: Archive production artifact - Linux
        uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          name: electron-linux-artifact
          path: dist_electron/job_desktop.AppImage

      - name: Archive production artifact - Windows
        uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          name: electron-windows-artifact
          path: dist_electron/job_desktop.exe

      - name: Archive production artifact - Mac
        uses: actions/upload-artifact@v2
        if: matrix.os == 'macos-latest'
        with:
          name: electron-mac-artifact
          path: dist_electron/job_desktop.dmg



